version: "3.7"

services: 
    angular-app:
        build: .
        ports: 
            - 4200:4200
            - 49153:49153
            - 9876:9876

        volumes:
        - ./src:/app/src
        - ./coverage:/app/coverage

        